--Create Database E_CommerceDB;

CREATE TABLE Category (
    Category_Id int NOT NULL PRIMARY KEY IDENTITY(1,1),
    Category_Name varchar(255),
);

CREATE TABLE Product (
    Product_Id int NOT NULL PRIMARY KEY IDENTITY(1,1),
	Product_Name varchar(255),
	Brand varchar(255),
    Category_Id int FOREIGN KEY REFERENCES Category (Category_Id),
    Price float(2),
);

CREATE TABLE Company (
    Company_Id int NOT NULL PRIMARY KEY IDENTITY(1,1),
    Company_Name varchar(255) NOT NULL,
    City varchar(255),
	VKN int
);
CREATE TABLE CustomerAdress (
    Customer_Id int NOT NULL PRIMARY KEY IDENTITY(1,1),
    Adress1 varchar(255),
	Adress2 varchar(255),
);

CREATE TABLE Customer (
    Customer_Id int NOT NULL PRIMARY KEY IDENTITY(1,1),
    Customer_Name varchar(255) NOT NULL,
    Customer_LastName varchar(255),
	Occupancy varchar(255),
	Customer_Adress int NOT NULL FOREIGN KEY REFERENCES CustomerAdress(Customer_Id),
);
CREATE TABLE OrderStatus (
    OrderStaus_Id int NOT NULL PRIMARY KEY IDENTITY(1,1),
    OrderStatus_name varchar(255),
);
CREATE TABLE Orders (
    Order_Id int NOT NULL PRIMARY KEY IDENTITY(1,1),
    Customer_Id int NOT NULL FOREIGN KEY REFERENCES Customer(Customer_Id),
    Company_Id int NOT NULL FOREIGN KEY REFERENCES Company(Company_Id),
    Product_Id int NOT NULL FOREIGN KEY REFERENCES Product(Product_Id),
	Order_Quantity int,
	Order_Price int,
	Order_Status_Id int NOT NULL FOREIGN KEY REFERENCES OrderStatus(OrderStaus_Id),
);


INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test1','Adress2_Test1')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test2','Adress2_Test2')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test3','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test4','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test5','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test6','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test7','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test8','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test9','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test10','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test11','Adress2_Test11')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test12','Adress2_Test12')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test13','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test14','Adress2_Test14')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test15','Adress2_Test15')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test16','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test17','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test18','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test19','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test20','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test21','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test22','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test23','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test24','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test25','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test26','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test27','Adress2_Test27')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test28','Adress2_Test28')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test29','Adress2_Test29')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test30','Adress2_Test30')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test31','Adress2_Test31')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test32','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test33','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test34','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test35','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test36','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test37','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test38','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test39','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test40','Adress2_Test40')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test41','Adress2_Test41')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test42','Adress2_Test42')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test43','Adress2_Test43')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test44','Adress2_Test44')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test45','Adress2_Test45')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test46','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test47','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test48','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test49','Adress2_Test49')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test50','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test51','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test52','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test53','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test54','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test55','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test56','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test57','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test58','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test59','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test60','Adress2_Test60')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test61','Adress2_Test61')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test62','Adress2_Test62')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test63','Adress2_Test63')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test64','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test65','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test66','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test67','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test68','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test69','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test70','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test71','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test72','Adress2_Test72')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test73','Adress2_Test73')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test74','Adress2_Test74')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test75','Adress2_Test75')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test76','Adress2_Test76')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test77','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test78','Adress2_Test78')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test79','Adress2_Test79')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test80','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test81','Adress2_Test81')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test82','Adress2_Test82')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test83','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test84','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test85','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test86','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test87','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test88','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test89','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test90','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test91','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test92','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test93','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test94','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test95','Adress2_Test95')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test96','Adress2_Test96')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test97','Adress2_Test97')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test98','')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test99','Adress2_Test99')
INSERT INTO CustomerAdress(Adress1,Adress2) VALUES ('Adress1_Test100','Adress2_Test100')

INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 1','TestLastName 1','Job1',1)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 2','TestLastName 2','Job2',2)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 3','TestLastName 3','Job3',3)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 4','TestLastName 4','Job4',4)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 5','TestLastName 65','Job5',5)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 6','TestLastName 6','Job6',6)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 7','TestLastName 7','Job7',7)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 8','TestLastName 8','Job8',8)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 9','TestLastName 9','Job9',9)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 10','TestLastName 10','Job3',10)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 11','TestLastName 11','Job11',11)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 12','TestLastName 12','Job12',12)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 13','TestLastName 13','Job13',13)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 14','TestLastName 97','Job14',14)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 15','TestLastName 15','Job15',15)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 16','TestLastName 16','Job16',16)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 17','TestLastName 17','Job17',17)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 18','TestLastName 18','Job18',18)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 19','TestLastName 19','Job19',19)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 20','TestLastName 20','Job20',20)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 21','TestLastName 21','Job21',21)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 22','TestLastName 22','Job22',22)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 23','TestLastName 23','Job23',23)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 24','TestLastName 24','Job24',24)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 25','TestLastName 25','Job25',25)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 26','TestLastName 26','Job26',26)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 27','TestLastName 27','Job27',27)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 28','TestLastName 28','Job28',28)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 29','TestLastName 29','Job29',29)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 30','TestLastName 30','Job30',30)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 31','TestLastName 31','Job31',31)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 32','TestLastName 32','Job32',32)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 33','TestLastName 33','Job33',33)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 34','TestLastName 47','Job34',34)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 35','TestLastName 35','Job15',35)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 36','TestLastName 36','Job36',36)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 37','TestLastName 37','Job37',37)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 38','TestLastName 38','Job38',38)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 39','TestLastName 39','Job39',39)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 40','TestLastName 40','Job40',40)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 41','TestLastName 41','Job41',41)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 42','TestLastName 42','Job42',42)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 43','TestLastName 43','Job43',43)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 44','TestLastName 44','Job44',44)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 45','TestLastName 45','Job45',45)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 46','TestLastName 84','Job46',46)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 47','TestLastName 47','Job47',47)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 48','TestLastName 48','Job48',48)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 49','TestLastName 3','Job49',49)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 50','TestLastName 50','Job50',50)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 51','TestLastName 51','Job31',51)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 52','TestLastName 52','Job52',52)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 53','TestLastName 53','Job53',53)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 54','TestLastName 54','Job54',54)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 55','TestLastName 55','Job55',55)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 56','TestLastName 56','Job56',56)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 57','TestLastName 57','Job57',57)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 58','TestLastName 58','Job58',58)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 59','TestLastName 59','Job59',59)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 60','TestLastName 31','Job60',60)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 61','TestLastName 61','Job61',61)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 62','TestLastName 62','Job62',62)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 63','TestLastName 63','Job47',63)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 64','TestLastName 81','Job64',64)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 65','TestLastName 65','Job65',65)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 66','TestLastName 66','Job66',66)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 67','TestLastName 67','Job67',67)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 68','TestLastName 68','Job68',68)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 69','TestLastName 69','Job69',69)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 70','TestLastName 70','Job70',70)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 71','TestLastName 97','Job71',71)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 72','TestLastName 72','Job89',72)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 73','TestLastName 73','Job90',73)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 74','TestLastName 74','Job91',74)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 75','TestLastName 75','Job75',75)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 76','TestLastName 76','Job76',76)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 77','TestLastName 77','Job56',77)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 78','TestLastName 78','Job57',78)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 79','TestLastName 79','Job58',79)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 80','TestLastName 80','Job59',80)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 81','TestLastName 81','Job81',81)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 82','TestLastName 82','Job82',82)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 83','TestLastName 83','Job83',83)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 84','TestLastName 84','Job84',84)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 85','TestLastName 85','Job85',85)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 86','TestLastName 86','Job86',86)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 87','TestLastName 87','Job87',87)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 88','TestLastName 88','Job88',88)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 89','TestLastName 89','Job89',89)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 90','TestLastName 90','Job90',90)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 91','TestLastName 91','Job91',91)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 92','TestLastName 92','Job92',92)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 93','TestLastName 93','Job93',93)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 94','TestLastName 94','Job94',94)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 95','TestLastName 95','Job95',95)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 96','TestLastName 96','Job71',96)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 97','TestLastName 97','Job72',97)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 98','TestLastName 98','Job73',98)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 99','TestLastName 99','Job99',99)
INSERT INTO Customer(Customer_Name,Customer_LastName,Occupancy,Customer_Adress) VALUES ('TestName 100','TestLastName 100','Job100',100)

INSERT INTO Category(Category_Name) VALUES ('Giyim')
INSERT INTO Category(Category_Name) VALUES ('Gýda')
INSERT INTO Category(Category_Name) VALUES ('Teknoloji')
INSERT INTO Category(Category_Name) VALUES ('Hýrdavat')
INSERT INTO Category(Category_Name) VALUES ('Oto')

INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 1','Brand1',1,410)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 2','Brand2',2,107)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 3','Brand3',4,566)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 4','Brand4',3,724)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 5','Brand5',3,282)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 6','Brand6',3,894)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 7','Brand7',4,16)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 8','Brand8',1,497)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 9','Brand9',4,827)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 10','Brand10',5,176)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 11','Brand11',3,451)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 12','Brand12',2,202)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 13','Brand13',3,245)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 14','Brand14',4,701)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 15','Brand15',1,640)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 16','Brand16',5,11)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 17','Brand17',2,506)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 18','Brand18',2,900)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 19','Brand19',3,572)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 20','Brand20',1,916)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 21','Brand21',2,124)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 22','Brand22',3,808)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 23','Brand23',4,728)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 24','Brand24',5,833)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 25','Brand25',1,340)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 26','Brand26',1,659)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 27','Brand27',1,473)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 28','Brand28',5,861)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 29','Brand29',3,327)
INSERT INTO Product(Product_Name,Brand,Category_Id,Price) VALUES ('TestProduct 30','Brand30',3,104)

INSERT INTO OrderStatus(OrderStatus_Name) VALUES ('Hazýrlanýyor')
INSERT INTO OrderStatus(OrderStatus_Name) VALUES ('Kargoda')
INSERT INTO OrderStatus(OrderStatus_Name) VALUES ('Teslim Edildi')

INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 1','Ýstanbul',99000223)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 2','Ýzmir',42774769)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 3','Bursa',81654507)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 4','Adana',91729844)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 5','Ankara',26800526)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 6','Ýstanbul',22694146)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 7','Bursa',65273320)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 8','Ýstanbul',43841569)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 9','Ankara',97391869)
INSERT INTO Company(Company_Name,City,VKN) VALUES ('TestCName 10','Ýstanbul',55150259)

INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (1,10,14,5,3505,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (77,5,18,3,2700,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (31,1,2,2,214,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (60,2,17,5,2530,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (39,6,23,3,2184,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (32,6,4,1,724,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (32,9,13,4,980,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (19,3,10,1,176,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (43,8,22,3,2424,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (27,9,15,3,1920,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (55,10,12,2,404,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (100,10,15,5,3200,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (72,2,17,3,1518,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (26,2,19,3,1716,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (18,5,19,2,1144,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (73,10,6,4,3576,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (12,9,22,2,1616,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (100,7,24,5,4165,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (4,4,20,3,2748,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (18,7,28,2,1722,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (2,5,3,1,566,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (84,10,19,3,1716,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (61,10,6,1,894,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (80,5,10,5,880,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (30,3,13,5,1225,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (85,1,4,5,3620,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (75,7,16,1,11,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (81,4,23,4,2912,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (95,6,7,3,48,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (15,2,12,4,808,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (56,10,1,1,410,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (26,8,10,1,176,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (49,10,21,3,372,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (100,7,18,5,4500,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (77,9,17,1,506,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (20,4,16,1,11,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (11,10,18,4,3600,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (72,7,1,1,410,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (60,1,30,2,208,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (72,4,3,1,566,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (16,2,16,2,22,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (74,7,25,1,340,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (99,2,29,3,981,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (59,9,19,2,1144,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (54,5,4,1,724,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (20,8,18,1,900,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (68,3,17,5,2530,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (70,6,25,5,1700,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (5,2,8,4,1988,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (80,1,12,4,808,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (53,5,8,2,994,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (66,5,23,2,1456,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (68,8,13,1,245,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (100,5,23,2,1456,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (99,9,5,1,282,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (12,1,9,4,3308,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (45,6,6,2,1788,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (75,6,8,4,1988,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (69,4,7,5,80,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (73,9,20,1,916,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (40,9,14,2,1402,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (17,7,9,4,3308,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (51,10,30,4,416,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (83,8,23,2,1456,2)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (61,2,9,4,3308,3)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (5,10,10,2,352,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (69,9,10,3,528,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (19,9,27,5,2365,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (52,2,28,5,4305,1)
INSERT INTO Orders(Customer_Id,Company_Id,Product_Id,Order_Quantity,Order_Price,Order_Status_Id) VALUES (10,1,19,1,572,1)